### PR TITLE
first pushmmm

### PR DESCRIPTION
**Pull request by cloudspace2**
dbhdbgdg

### CODE REVIEW

**Comment by benahoure** [comment]
This code looks good. Approved

**Comment by huglaure** [comment]
awesome

**Review by Dreany-drew — APPROVED** [review]

**Review by benahoure — CHANGES_REQUESTED** [review]
I like you to update it this way... 
module "autoscaling" {
  source  = "terraform-aws-modules/autoscaling/aws"
  version = "4.9.0"

  # Autoscaling group
  name = "myasg"

  vpc_zone_identifier = [aws_subnet.private_subnets["private_subnet_1"].id, 
  aws_subnet.private_subnets["private_subnet_2"].id, 
  aws_subnet.private_subnets["private_subnet_3"].id]
  min_size            = 0
  max_size            = 1
  desired_capacity    = 1

  # Launch template
  use_lt    = true
  create_lt = true

  image_id      = data.aws_ami.ubuntu.id
  instance_type = "t3.micro"

  tags_as_map = {
    Name = "Web EC2 Server 2"
  }

}

**Review by benahoure — APPROVED** [review]
Looks good now. Thanks for the change.

**Review by tcheumeni — APPROVED** [review]
looks good for me.

**Pull request merged**
